@endpoint = https://6r93kixotj.execute-api.us-east-1.amazonaws.com/prod/

GET {{endpoint}}/spaces
###

GET {{endpoint}}/spaces?spaceId=62441029-e571-449c-a9e0-d068509a540a
###

GET {{endpoint}}/spaces?location=France
###


POST {{endpoint}}/spaces/
Content-Type: application/json

{
    "location": "France",
    "name": "New Location"
}
###


PUT {{endpoint}}/spaces?spaceId=62441029-e571-449c-a9e0-d068509a540a
Content-Type: application/json
{
    "location": "Updated Location"
}
###


DELETE {{endpoint}}/spaces?spaceId=438eec4d-c09a-45eb-b795-c92e4d9d3ff6
###